# First User ID = "6695476cd4c69e4c1d57c5de"
# First Note ID = "669548ce40373f7fb0951000"

#!  Get all users
GET http://localhost:3001/api/users
Content-Type: application/json


###
#! Create a new user
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "test-two",
    "password": "test1234"
}

###
#! update user
PATCH http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "id": "6695476cd4c69e4c1d57c5de",
    "active": true
}
###

#! Delete user
DELETE http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "id": "66955913cb115f5a2932a91f"
}

###
#! Login
POST http://localhost:3001/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "test-temp",
    "password": "test123"
}